version: "3.8"
services:
  postgres-compose:
    container_name: pg_container
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - I:/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: socorristaDB
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge