version: '3.8'
services:
  
  api:
    image: 'hmv-api'
    build:
      context: fiap_hmv-api/
    container_name: hmv-api
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/socorristaDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    networks:
      - hmv-network
    ports:
      - "8080:8080"
          
  db:
    image: 'postgres:14.2-alpine'
    container_name: db-postgres
    volumes:
      - db-data:/var/lib/postgresql/data 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: socorristaDB
    networks:
      - hmv-network
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - hmv-network

  app:
    image: 'hmv-app'
    restart: always
    build:
      context: hmv_fiap/
    networks:
      - hmv-network
    ports:
      - "80:80"
      - "443:443"
networks: 
  hmv-network:
    driver: bridge
volumes:
  db-data: